# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_service/v1/model_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'model_service/v1/model_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$model_service/v1/model_service.proto\x12\x10model_service.v1\"\x84\x01\n\x05State\x12%\n\x05\x62oard\x18\x01 \x03(\x0e\x32\x16.model_service.v1.Cell\x12\'\n\x07\x63urrent\x18\x02 \x01(\x0e\x32\x16.model_service.v1.Cell\x12+\n\x0blegal_moves\x18\x03 \x03(\x0b\x32\x16.model_service.v1.Move\"w\n\x11SelectMoveRequest\x12&\n\x05state\x18\x01 \x01(\x0b\x32\x17.model_service.v1.State\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x18\n\x0btemperature\x18\x03 \x01(\x02H\x00\x88\x01\x01\x42\x0e\n\x0c_temperature\" \n\x04Move\x12\x0b\n\x03row\x18\x01 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x02 \x01(\x05\"k\n\x12SelectMoveResponse\x12$\n\x04move\x18\x01 \x01(\x0b\x32\x16.model_service.v1.Move\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x0e\n\x06policy\x18\x03 \x03(\x02\x12\x10\n\x08model_id\x18\x04 \x01(\t*6\n\x04\x43\x65ll\x12\x0e\n\nCELL_EMPTY\x10\x00\x12\x0e\n\nCELL_WHITE\x10\x01\x12\x0e\n\nCELL_BLACK\x10\x02\x32g\n\x0cModelService\x12W\n\nSelectMove\x12#.model_service.v1.SelectMoveRequest\x1a$.model_service.v1.SelectMoveResponseBEZCgithub.com/ArthurMukha/reversi-rl-agent/game-service/internal/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_service.v1.model_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZCgithub.com/ArthurMukha/reversi-rl-agent/game-service/internal/pb;pb'
  _globals['_CELL']._serialized_start=457
  _globals['_CELL']._serialized_end=511
  _globals['_STATE']._serialized_start=59
  _globals['_STATE']._serialized_end=191
  _globals['_SELECTMOVEREQUEST']._serialized_start=193
  _globals['_SELECTMOVEREQUEST']._serialized_end=312
  _globals['_MOVE']._serialized_start=314
  _globals['_MOVE']._serialized_end=346
  _globals['_SELECTMOVERESPONSE']._serialized_start=348
  _globals['_SELECTMOVERESPONSE']._serialized_end=455
  _globals['_MODELSERVICE']._serialized_start=513
  _globals['_MODELSERVICE']._serialized_end=616
# @@protoc_insertion_point(module_scope)
