// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: model_service/v1/model_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelService_SelectMove_FullMethodName = "/model_service.v1.ModelService/SelectMove"
)

// ModelServiceClient is the client API for ModelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Контракт между игровым сервисом на Go и сервисом модели на Python.
//
// Правила игры живут ТОЛЬКО в Go. Модель их не знает: получает позицию
// и список легальных ходов, возвращает выбранный.
//
// Запрос не имеет состояния — каждый вызов несёт полную позицию. Поэтому
// сервис модели можно перезапустить посреди партии, и никто не заметит.
type ModelServiceClient interface {
	SelectMove(ctx context.Context, in *SelectMoveRequest, opts ...grpc.CallOption) (*SelectMoveResponse, error)
}

type modelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelServiceClient(cc grpc.ClientConnInterface) ModelServiceClient {
	return &modelServiceClient{cc}
}

func (c *modelServiceClient) SelectMove(ctx context.Context, in *SelectMoveRequest, opts ...grpc.CallOption) (*SelectMoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectMoveResponse)
	err := c.cc.Invoke(ctx, ModelService_SelectMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelServiceServer is the server API for ModelService service.
// All implementations must embed UnimplementedModelServiceServer
// for forward compatibility.
//
// Контракт между игровым сервисом на Go и сервисом модели на Python.
//
// Правила игры живут ТОЛЬКО в Go. Модель их не знает: получает позицию
// и список легальных ходов, возвращает выбранный.
//
// Запрос не имеет состояния — каждый вызов несёт полную позицию. Поэтому
// сервис модели можно перезапустить посреди партии, и никто не заметит.
type ModelServiceServer interface {
	SelectMove(context.Context, *SelectMoveRequest) (*SelectMoveResponse, error)
	mustEmbedUnimplementedModelServiceServer()
}

// UnimplementedModelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelServiceServer struct{}

func (UnimplementedModelServiceServer) SelectMove(context.Context, *SelectMoveRequest) (*SelectMoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectMove not implemented")
}
func (UnimplementedModelServiceServer) mustEmbedUnimplementedModelServiceServer() {}
func (UnimplementedModelServiceServer) testEmbeddedByValue()                      {}

// UnsafeModelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelServiceServer will
// result in compilation errors.
type UnsafeModelServiceServer interface {
	mustEmbedUnimplementedModelServiceServer()
}

func RegisterModelServiceServer(s grpc.ServiceRegistrar, srv ModelServiceServer) {
	// If the following call panics, it indicates UnimplementedModelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelService_ServiceDesc, srv)
}

func _ModelService_SelectMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).SelectMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_SelectMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).SelectMove(ctx, req.(*SelectMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelService_ServiceDesc is the grpc.ServiceDesc for ModelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model_service.v1.ModelService",
	HandlerType: (*ModelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectMove",
			Handler:    _ModelService_SelectMove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model_service/v1/model_service.proto",
}
