// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: model_service/v1/model_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Значения совпадают с game.Cell в Go, но владеет ими контракт:
// Python не должен полагаться на то, что «там так же».
type Cell int32

const (
	Cell_CELL_EMPTY Cell = 0
	Cell_CELL_WHITE Cell = 1
	Cell_CELL_BLACK Cell = 2
)

// Enum value maps for Cell.
var (
	Cell_name = map[int32]string{
		0: "CELL_EMPTY",
		1: "CELL_WHITE",
		2: "CELL_BLACK",
	}
	Cell_value = map[string]int32{
		"CELL_EMPTY": 0,
		"CELL_WHITE": 1,
		"CELL_BLACK": 2,
	}
)

func (x Cell) Enum() *Cell {
	p := new(Cell)
	*p = x
	return p
}

func (x Cell) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cell) Descriptor() protoreflect.EnumDescriptor {
	return file_model_service_v1_model_service_proto_enumTypes[0].Descriptor()
}

func (Cell) Type() protoreflect.EnumType {
	return &file_model_service_v1_model_service_proto_enumTypes[0]
}

func (x Cell) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cell.Descriptor instead.
func (Cell) EnumDescriptor() ([]byte, []int) {
	return file_model_service_v1_model_service_proto_rawDescGZIP(), []int{0}
}

// Позиция на доске. Без настроек вызова — они уровнем выше.
type State struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ровно 64 клетки, row-major: индекс = row * 8 + col.
	// Вложенный repeated в proto3 запрещён, поэтому массив плоский,
	// а длину приходится проверять на приёме руками.
	Board []Cell `protobuf:"varint,1,rep,packed,name=board,proto3,enum=model_service.v1.Cell" json:"board,omitempty"`
	// Чей ход. Из board не выводится, поэтому передаётся явно:
	// сеть ест не абсолютные цвета, а планы «мои фишки / чужие фишки».
	Current Cell `protobuf:"varint,2,opt,name=current,proto3,enum=model_service.v1.Cell" json:"current,omitempty"`
	// Считает Go. Python принимает на веру и не выбирает за пределами списка.
	// Пустой список — ошибка запроса (INVALID_ARGUMENT), а не «пас»:
	// пасы обрабатывает Go, до модели такая позиция доходить не должна.
	LegalMoves    []*Move `protobuf:"bytes,3,rep,name=legal_moves,json=legalMoves,proto3" json:"legal_moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_model_service_v1_model_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_model_service_v1_model_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_model_service_v1_model_service_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetBoard() []Cell {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *State) GetCurrent() Cell {
	if x != nil {
		return x.Current
	}
	return Cell_CELL_EMPTY
}

func (x *State) GetLegalMoves() []*Move {
	if x != nil {
		return x.LegalMoves
	}
	return nil
}

type SelectMoveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State *State                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// Какой моделью отвечать. Неизвестная — NOT_FOUND.
	ModelId string `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// 0 — детерминированный выбор (argmax), больше — тем случайнее.
	// optional здесь обязателен: у proto3 дефолт float равен нулю, и без
	// явного отслеживания присутствия «клиент не передал» неотличимо от
	// «клиент передал 0». Иначе забытое поле молча включает argmax.
	Temperature   *float32 `protobuf:"fixed32,3,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectMoveRequest) Reset() {
	*x = SelectMoveRequest{}
	mi := &file_model_service_v1_model_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectMoveRequest) ProtoMessage() {}

func (x *SelectMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_service_v1_model_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectMoveRequest.ProtoReflect.Descriptor instead.
func (*SelectMoveRequest) Descriptor() ([]byte, []int) {
	return file_model_service_v1_model_service_proto_rawDescGZIP(), []int{1}
}

func (x *SelectMoveRequest) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SelectMoveRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SelectMoveRequest) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           int32                  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col           int32                  `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_model_service_v1_model_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_model_service_v1_model_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_model_service_v1_model_service_proto_rawDescGZIP(), []int{2}
}

func (x *Move) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Move) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

type SelectMoveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Выбранный ход. Доску не применяем и фишки не переворачиваем —
	// это делает Go, правила его.
	Move *Move `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
	// Оценка позиции ОТ ЛИЦА state.current: +1 — выигрывает тот, чей ход.
	// Перспектива именно такая, потому что вход сети собран от него же.
	Value float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	// Ровно 64 значения, тот же порядок, что у board.
	// Это распределение ПОСЛЕ маски: сумма равна 1, на нелегальных ходах нули.
	// Считается при температуре 1 независимо от temperature запроса —
	// policy означает «что думает сеть», а temperature только «как выбирали».
	Policy []float32 `protobuf:"fixed32,3,rep,packed,name=policy,proto3" json:"policy,omitempty"`
	// Какая модель реально ответила.
	ModelId       string `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectMoveResponse) Reset() {
	*x = SelectMoveResponse{}
	mi := &file_model_service_v1_model_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectMoveResponse) ProtoMessage() {}

func (x *SelectMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_service_v1_model_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectMoveResponse.ProtoReflect.Descriptor instead.
func (*SelectMoveResponse) Descriptor() ([]byte, []int) {
	return file_model_service_v1_model_service_proto_rawDescGZIP(), []int{3}
}

func (x *SelectMoveResponse) GetMove() *Move {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *SelectMoveResponse) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SelectMoveResponse) GetPolicy() []float32 {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *SelectMoveResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

var File_model_service_v1_model_service_proto protoreflect.FileDescriptor

const file_model_service_v1_model_service_proto_rawDesc = "" +
	"\n" +
	"$model_service/v1/model_service.proto\x12\x10model_service.v1\"\xa0\x01\n" +
	"\x05State\x12,\n" +
	"\x05board\x18\x01 \x03(\x0e2\x16.model_service.v1.CellR\x05board\x120\n" +
	"\acurrent\x18\x02 \x01(\x0e2\x16.model_service.v1.CellR\acurrent\x127\n" +
	"\vlegal_moves\x18\x03 \x03(\v2\x16.model_service.v1.MoveR\n" +
	"legalMoves\"\x94\x01\n" +
	"\x11SelectMoveRequest\x12-\n" +
	"\x05state\x18\x01 \x01(\v2\x17.model_service.v1.StateR\x05state\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12%\n" +
	"\vtemperature\x18\x03 \x01(\x02H\x00R\vtemperature\x88\x01\x01B\x0e\n" +
	"\f_temperature\"*\n" +
	"\x04Move\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\x02 \x01(\x05R\x03col\"\x89\x01\n" +
	"\x12SelectMoveResponse\x12*\n" +
	"\x04move\x18\x01 \x01(\v2\x16.model_service.v1.MoveR\x04move\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\x12\x16\n" +
	"\x06policy\x18\x03 \x03(\x02R\x06policy\x12\x19\n" +
	"\bmodel_id\x18\x04 \x01(\tR\amodelId*6\n" +
	"\x04Cell\x12\x0e\n" +
	"\n" +
	"CELL_EMPTY\x10\x00\x12\x0e\n" +
	"\n" +
	"CELL_WHITE\x10\x01\x12\x0e\n" +
	"\n" +
	"CELL_BLACK\x10\x022g\n" +
	"\fModelService\x12W\n" +
	"\n" +
	"SelectMove\x12#.model_service.v1.SelectMoveRequest\x1a$.model_service.v1.SelectMoveResponseBEZCgithub.com/ArthurMukha/reversi-rl-agent/game-service/internal/pb;pbb\x06proto3"

var (
	file_model_service_v1_model_service_proto_rawDescOnce sync.Once
	file_model_service_v1_model_service_proto_rawDescData []byte
)

func file_model_service_v1_model_service_proto_rawDescGZIP() []byte {
	file_model_service_v1_model_service_proto_rawDescOnce.Do(func() {
		file_model_service_v1_model_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_service_v1_model_service_proto_rawDesc), len(file_model_service_v1_model_service_proto_rawDesc)))
	})
	return file_model_service_v1_model_service_proto_rawDescData
}

var file_model_service_v1_model_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_model_service_v1_model_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_model_service_v1_model_service_proto_goTypes = []any{
	(Cell)(0),                  // 0: model_service.v1.Cell
	(*State)(nil),              // 1: model_service.v1.State
	(*SelectMoveRequest)(nil),  // 2: model_service.v1.SelectMoveRequest
	(*Move)(nil),               // 3: model_service.v1.Move
	(*SelectMoveResponse)(nil), // 4: model_service.v1.SelectMoveResponse
}
var file_model_service_v1_model_service_proto_depIdxs = []int32{
	0, // 0: model_service.v1.State.board:type_name -> model_service.v1.Cell
	0, // 1: model_service.v1.State.current:type_name -> model_service.v1.Cell
	3, // 2: model_service.v1.State.legal_moves:type_name -> model_service.v1.Move
	1, // 3: model_service.v1.SelectMoveRequest.state:type_name -> model_service.v1.State
	3, // 4: model_service.v1.SelectMoveResponse.move:type_name -> model_service.v1.Move
	2, // 5: model_service.v1.ModelService.SelectMove:input_type -> model_service.v1.SelectMoveRequest
	4, // 6: model_service.v1.ModelService.SelectMove:output_type -> model_service.v1.SelectMoveResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_model_service_v1_model_service_proto_init() }
func file_model_service_v1_model_service_proto_init() {
	if File_model_service_v1_model_service_proto != nil {
		return
	}
	file_model_service_v1_model_service_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_service_v1_model_service_proto_rawDesc), len(file_model_service_v1_model_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_service_v1_model_service_proto_goTypes,
		DependencyIndexes: file_model_service_v1_model_service_proto_depIdxs,
		EnumInfos:         file_model_service_v1_model_service_proto_enumTypes,
		MessageInfos:      file_model_service_v1_model_service_proto_msgTypes,
	}.Build()
	File_model_service_v1_model_service_proto = out.File
	file_model_service_v1_model_service_proto_goTypes = nil
	file_model_service_v1_model_service_proto_depIdxs = nil
}
